HackslashForum/HackslashForum/Controllers/PostsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using HackslashForum;
using HackslashForum.Data;
using System.Collections;
using Microsoft.AspNetCore.Identity;
using HackslashForum.Models;
using Microsoft.AspNetCore.Http;
using System.IO;
using HackslashForum.Models.ManageViewModels;

namespace HackslashForum.Controllers
{
    public class PostsController : Controller
    {
        private readonly ApplicationDbContext _context;
        private readonly UserManager<ApplicationUser> _manager;
        private readonly SignInManager<ApplicationUser> _signInManager;

        public PostsController(ApplicationDbContext context, UserManager<ApplicationUser> manager, SignInManager<ApplicationUser> signInManager)
        {
            _context = context;
            _manager = manager;
            _signInManager = signInManager;
        }

        // GET: Posts
        public async Task<IActionResult> Index()
        {
         
            return View(await _context.Post.ToListAsync());
        }

        // GET: Posts/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Post.Include(u => u.User)
                .SingleOrDefaultAsync(m => m.Id == id);

            if (post == null)
            {
                return NotFound();
            }

            return View(post);
        }

        public async Task<IActionResult> Post(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var post = await _context.Post.Include(p => p.UsersWhoVoted)
                .SingleOrDefaultAsync(m => m.Id == id);

            if (post == null)
            {
                return NotFound();
            }

            var postAuthor = _context.User.Where(p => p.Id == post.UserId).Take(1).SingleOrDefault();
            IndexViewModel model = null;

            if(postAuthor.ProfilePicture != null)
            {
                string base64 = Convert.ToBase64String(postAuthor.ProfilePicture);
                string imgSrc = String.Format("data:image/png;base64,{0}", base64);
                model = new IndexViewModel
                {
                    ImgSrc = imgSrc,
                };
            }

            //                  I
            //Detta funkar inte v

            //var user = await _manager.GetUserAsync(User);

            //string base64 = "";
            //string imgSrc = "";
            //if (user.ProfilePicture != null)
            //{
            //    base64 = Convert.ToBase64String(user.ProfilePicture);
            //    imgSrc = String.Format("data:image/png;base64,{0}", base64);
            //}
            //var model = new IndexViewModel
            //{

            //    ImgSrc = imgSrc,
            //};

            //ViewBag.ProfilePicture = model.ImgSrc;

            if (postAuthor.ProfilePicture != null)
                ViewBag.PostAuthorProfilePicture = model.ImgSrc;
            else
                ViewBag.PostAuthorProfilePicture = null;


            ViewBag.TotalScore = post.UpVotes - post.DownVotes;

            ViewBag.Comments = (from x in _context.Comment
                                where x.Post.Id == id
                                select x).ToList();

            ViewBag.PostAuthor = (from y in _context.Post
                                 where y.Id == id.Value
                                 select y.User.UserName).Single();

            ViewBag.CommentAuthor = (from x in _context.User
                                     join y in _context.Comment on x.Id equals y.User.Id
                                     select x.UserName).Take(1).SingleOrDefault();

            return View(post);
        }

        public async Task<IActionResult> Comment(int? id, string content)
        {
            if (id == null)
                return NotFound();

            var post = (from p in _context.Post
                       where p.Id == id
                       select p).Take(1).SingleOrDefault();

            var user = await _signInManager.UserManager.GetUserAsync(User);

            Comment comment = new Comment
            {
                User = user,
                UserId = user.Id,
                Author = user.UserName,
                Post = post,
                PostId = post.Id,
                DateTimeCommentMade = DateTime.Now,
                Content = content
            };

            _context.Comment.Add(comment);
            _context.SaveChanges();

            return RedirectToAction($"Post/{id}");
        }

        public async Task<IActionResult> Upvote(int? id)
        {
            if (id == null)
                return NotFound();

            var post = _context.Post.Include(p => p.UsersWhoVoted).SingleOrDefault(p => p.Id == id);

            var user = await _signInManager.UserManager.GetUserAsync(User);

            var UserVoteModel = _context.VotedUsers.Where(p => p.PostId == id).Where(p => p.UserId == user.Id).Take(1).SingleOrDefault();

            UserVoteModel VotedUser = null;

            if(UserVoteModel == null)
            {
                VotedUser = new UserVoteModel
                {
                    Post = post,
                    PostId = post.Id,
                    User = user,
                    UserId = user.Id,
                    Vote = Vote.Up
                };
                post.UpVotes++;
                _context.Update(post);
                _context.VotedUsers.Add(VotedUser);
            }
            else
            {
                UserVoteModel.Vote = Vote.Up;
                post.UpVotes++;
                post.DownVotes--;
                _context.Update(post);
                _context.VotedUsers.Update(UserVoteModel);
            }
            _context.SaveChanges();

            return RedirectToAction($"Post/{id}");
        }

        public async Task<IActionResult> Downvote(int? id)
        {
            if (id == null)
                return NotFound();

            var post = _context.Post.Include(p => p.UsersWhoVoted).SingleOrDefault(p => p.Id == id);

            var user = await _signInManager.UserManager.GetUserAsync(User);

            var UserVoteModel = _context.VotedUsers.Where(p => p.PostId == id).Where(p => p.UserId == user.Id).Take(1).SingleOrDefault();

            UserVoteModel VotedUser = null;

            if (UserVoteModel == null)
            {
                VotedUser = new UserVoteModel
                {
                    Post = post,
                    PostId = post.Id,
                    User = user,
                    UserId = user.Id,
                    Vote = Vote.Down
                };
                post.DownVotes++;
                _context.Update(post);
                _context.VotedUsers.Add(VotedUser);
            }
            else
            {
                UserVoteModel.Vote = Vote.Down;
                post.DownVotes++;
                post.UpVotes--;
                _context.Update(post);
                _context.VotedUsers.Update(UserVoteModel);
            }
            _context.SaveChanges();

            return RedirectToAction($"Post/{id}");
        }

        public async Task<IActionResult> UpvoteComment(int? id)
        {
            if (id == null)
                return NotFound();

            var comment = _context.Comment.Where(p => p.ID == id).Take(1).SingleOrDefault();

            var post = _context.Post.Where(p => p.Id == comment.PostId).Take(1).SingleOrDefault();

            var user = await _signInManager.UserManager.GetUserAsync(User);

            var VotedCommentModel = _context.VotedComments.Where(p => p.CommentId == id).Where(p => p.UserId == user.Id).Take(1).SingleOrDefault();

            VoteOnCommentModel VotedComment = null;

            if (VotedCommentModel == null)
            {
                VotedComment = new VoteOnCommentModel
                {
                    Comment = comment,
                    CommentId = comment.ID,
                    User = user,
                    UserId = user.Id,
                    Vote = Vote.Up
                };
                comment.Upvotes++;
                _context.Update(comment);
                _context.VotedComments.Add(VotedComment);
            }
            else
            {
                VotedCommentModel.Vote = Vote.Up;
                comment.Upvotes++;
                comment.Downvotes--;
                _context.Update(comment);
                _context.VotedComments.Update(VotedCommentModel);
            }
            _context.SaveChanges();

            return RedirectToAction($"Post/{post.Id}");
        }

        public async Task<IActionResult> DownvoteComment(int? id)
        {
            if (id == null)
                return NotFound();

            var comment = _context.Comment.Where(p => p.ID == id).Take(1).SingleOrDefault();

            var post = _context.Post.Where(p => p.Id == comment.PostId).Take(1).SingleOrDefault();

            var user = await _signInManager.UserManager.GetUserAsync(User);

            var VotedCommentModel = _context.VotedComments.Where(p => p.CommentId == id).Where(p => p.UserId == user.Id).Take(1).SingleOrDefault();

            VoteOnCommentModel VotedComment = null;

            if (VotedCommentModel == null)
            {
                VotedComment = new VoteOnCommentModel
                {
                    Comment = comment,
                    CommentId = comment.ID,
                    User = user,
                    UserId = user.Id,
                    Vote = Vote.Down
                };
                comment.Downvotes++;
                _context.Update(comment);
                _context.VotedComments.Add(VotedComment);

HackslashForum/HackslashForum/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="sv">
<head>
	<meta charset="utf-8" />
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<title>@ViewData["Title"] - HackslashForum</title>
	<link rel="icon" type="images/png" href="~/images/hackSlashLogo.png" sizes="16x16" />
	<link href="https://fonts.googleapis.com/css?family=Audiowide" rel="stylesheet">
	<link href="https://fonts.googleapis.com/css?family=Orbitron" rel="stylesheet">

	<environment include="Development">
		<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
		<link rel="stylesheet" href="~/css/site.css" />
	</environment>
	<environment exclude="Development">
		<link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
			  asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
			  asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
		<link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
	</environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top spaceFont">
        <div class="container">
            <div class="header" style="margin-top:10px;">
                <a style="float:left;" href="/Home/Index/"><img src="~/images/hackSlashLogo.png" style="width:100px;height:100px;"></a>
                <h1 style="margin-left: 20px;margin-top: 25px;float: left;color:white; font-family:Audiowide">HackSlash</h1>

                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div class="navbar-collapse collapse">
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content content">
        @RenderBody()
    </div>
    <div id="footer-nav">
        <footer>
            <p>&copy; 2018 - HackslashForum - Göteborg - IT-Högskolan </p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

HackslashForum/HackslashForum/Views/Shared/_LoginComment.cshtml
@using Microsoft.AspNetCore.Identity
@using HackslashForum.Models

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    <form asp-action="Comment" asp-route-id="@Model.Id" asp-controller="Posts">
        <textarea name="content" style="min-width:100%;max-width:100%;min-height:26px;"></textarea>
        <br />
        <input type="submit" value="Kommentera" />
    </form>
}

HackslashForum/HackslashForum/Views/Shared/_LoginDownvote.cshtml
@model Post

@using Microsoft.AspNetCore.Identity
@using HackslashForum.Models
@using HackslashForum.Data

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@inject ApplicationDbContext _context;

@if (SignInManager.IsSignedIn(User))
{
    var user = await SignInManager.UserManager.GetUserAsync(User);

    var VotedPost = _context.VotedUsers.Where(p => p.PostId == Model.Id).Where(p => p.UserId == user.Id).Take(1).SingleOrDefault();
    
    if (VotedPost != null && VotedPost.Vote == Vote.Down) {
        <form asp-action="Downvote" asp-route-id="@Model.Id" asp-controller="Posts">
            <span>
                <img src="~/images/Downvote.png" style="height: 20px; width: 20px; filter: brightness(100%);" />
            </span>
        </form>
    }
    else
    {
        <form asp-action="Downvote" asp-route-id="@Model.Id" asp-controller="Posts">
            <span>
                <input type="image" src="~/images/Downvote.png" alt="Submit" value="downvote" style="height: 20px; width: 20px; filter: brightness(50%);" />
            </span>
        </form>
    }

}

HackslashForum/HackslashForum/Views/Shared/_LoginUpvote.cshtml
@model Post

@using Microsoft.AspNetCore.Identity
@using HackslashForum.Models
@using HackslashForum.Data

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager
@inject ApplicationDbContext _context;

@if (SignInManager.IsSignedIn(User))
{
    var user = await SignInManager.UserManager.GetUserAsync(User);

    var VotedPost = _context.VotedUsers.Where(p => p.PostId == Model.Id).Where(p => p.UserId == user.Id).Take(1).SingleOrDefault();

    if (VotedPost != null && VotedPost.Vote == Vote.Up)
    {
        <form asp-action="Upvote" asp-route-id="@Model.Id" asp-controller="Posts">
            <span>
                <img src="~/images/Upvote.png" style="height: 20px; width: 20px; filter: brightness(100%);" />
            </span>
        </form>
    }
    else
    {
        <form asp-action="Upvote" asp-route-id="@Model.Id" asp-controller="Posts">
            <span>
                <input type="image" src="~/images/Upvote.png" alt="Submit" value="upvote" style="height: 20px; width: 20px; filter: brightness(50%);" />
            </span>
        </form>
    }

    
}